---
title: "Automatic Report of Country through API call"
output:
    html_document:
      toc: true
      fig_crop: no
      toc_float: true
    pdf_document:
      toc: true
      fig_crop: no
params:
  acled_email: email  
  acled_key: key   
  end_date: !r Sys.Date()
  country: country          
  printcode: TRUE 
  start_date: "1997-01-01"
  data: data
subtitle: "Country: `r params$country` - From: `r params$start_date` to `r params$end_date`"  

---

<style type="text/css">
.main-container {
  max-width: 1400px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r loading what we need, echo=FALSE}
library(acledR)
library(knitr)
library(kableExtra)
library(dplyr)
library(tidyr)
library(plotly)
library(viridis)
library(mapview)
library(stringr)
library(sf)

defaultW <- getOption("warn") 

options(warn = -1)


```

## 1. General statistics

```{r table of statistics, echo=FALSE}


table_data_source <- acled_transform(params$data, type = "source") %>%
  group_by(source) %>%
  summarise(frequency = n()) %>%
  arrange(-frequency)

unique_number_of_sources <- length(unique(table_data_source$source))

table_data_actor <- acled_transform(params$data, type = "full_actors")%>%
  group_by(actor) %>%
  summarise(frequency = n()) %>%
  arrange(-frequency)

unique_number_of_actors <- length(unique(table_data_actor$actor))


table_data <- params$data %>%
  mutate(event_date = as.character(event_date))%>%
  group_by(country) %>%
  summarise(total_events = n(),
            total_fatalities = sum(fatalities),
            eventful_days = n_distinct(event_date))
table_data$total_actors <- unique_number_of_actors
table_data$total_sources <- unique_number_of_sources

kbl(table_data) %>%
  kable_styling()



```

### 1.1 Most Frequent Sources

```{r sources brealdown, echo = FALSE, fig.align='right',fig.width=10,fig.height=7}
su <- ggplot(slice_max(.data = table_data_source,order_by = frequency, n=30),aes(frequency,reorder(source,frequency),fill=source,text=c(paste0("Source: ", source,"\n","Frequency: ", frequency)))) +
  geom_bar(stat="identity",fill= "slateblue3")+
  theme(legend.position = "none")+
  labs(title = "Top 30 most frequent sources utilized in the dataset",
       x= "Frequency",
       y= "Source")
ggplotly(su,tooltip = "text")
```

### 1.2 Most Frequent Actors

```{r actor breakdown, echo = FALSE, fig.align='right',fig.width=10,fig.height=7}
fu <- ggplot(slice_max(table_data_actor,order_by = frequency,n=30),
             aes(frequency,reorder(actor,frequency),text=c(paste0("Actor: ", actor,"\n","Frequency: ", frequency))))+
  geom_bar(stat="identity", fill= "slateblue3")+
  theme(legend.position="none")+
  labs(title = "Top 30 most frequent actors in the dataset",
       x="Frequency",
       y="Actor")

ggplotly(fu, tooltip = "text")
```

### 1.3 Sub-Event Types frequencies

```{r Sub-Event type,echo = FALSE, fig.align='right',fig.width=10,fig.height=7}
sub_event_table <- params$data %>%
  group_by(event_type,sub_event_type) %>%
  summarise(frequency = n()) %>%
  filter(event_type != "Strategic developments")

zu <-ggplot(sub_event_table,aes(x=frequency,fill=event_type,
                                text= c(
                                  paste0("Sub-Event type: ", sub_event_type,"\n",
                                         "Event Type: ",event_type, "\n",
                                         "Frequency: ", frequency))))+
      geom_bar(aes(y=reorder(sub_event_type,frequency)),stat="identity", size=10)+
      scale_x_continuous(trans="log10")+
      labs(title = "Magnitude of Sub-Event types in a log10 scale",
           x="Frequency in a 10 logarithmic scale",
           y="Sub-Event Types",
           fill = "Event Types")

ggplotly(zu, tooltip = "text")

```

## 2. Monthly average of events in `r params$country`

```{r moving avergeas, echo = FALSE, fig.align='right',fig.width=10,fig.height=7}

df1 <- params$data %>%
  generate_counts(.,
                  unit_id = "country",
                  time_id = "event_date",
                  time_target = "month")

# Generate 3 moving average of total events per month
df1m <-
  generate_movers(data = df1,
                  var = "total_events",
                  unit_id = "country",
                  time_id = "event_month",
                  slide_funs = "mean",
                  slide_periods = 3)

average_per_year <- df1 %>%
  mutate(year = lubridate::floor_date(event_month,unit = "year")) %>%
  group_by(year) %>%
  summarise(average_events_per_month = mean(total_events))

ha <- ggplot(df1m, aes(x=event_month, text = paste0("Month & Year: ",lubridate::format_ISO8601(event_month,precision = "ym"),"\n","3 months moving average: ", total_events_moving_mean_3, "\n", "Total number of events this month: ", total_events)))+
    geom_point(aes(y=total_events))+
    geom_line(aes(y=total_events_moving_mean_3, group=1, color = "3 Months Moving Average"))+
    # geom_line(data=average_per_year,aes(x=year,y=average_events_per_month), color = "green")+
    labs(title = paste0("Moving 3 months average of total events in ", params$country),
         x= "Month - Year",
         y= "Number of Events")+
     scale_colour_manual(name = 'Legend',
         values=c('3 Months Moving Average' = 'blue'))

ggplotly(ha, tooltip = "text")

```



## 3. Map of events distribution in the country per admin1 levels

```{r map of stuff,echo = FALSE, fig.align='right',fig.width=10,fig.height=7}


admin1_country <- raster::getData(name = "GADM", country = params$country, level = 1) %>%
  # convert to sf object
  st_as_sf()

country_counts <-
  params$data %>% 
  # full_join(select(admin1_country, NAME_1, NAME_0), by = c("admin1" = "NAME_1", "country" = "NAME_0")) %>% 
  group_by(admin1) %>% 
  tally() %>% 
  full_join(admin1_country, by = c("admin1" = "NAME_1")) %>% 
  mutate(n = case_when(
    is.na(n) ~ 0L,
    TRUE ~ n
  )) %>%
  sf::st_as_sf()

library(mapview)
mapviewOptions(fgb = FALSE) # needed when creating web pages
mapview(country_counts["n"], at = seq(1,2500,200))

```
