#' @name acled_access
#' @title Store your ACLED access information into your session.
#' @description Simple function to store (through `Sys.setenv()` ) ACLED access keys for the acled_api() function.
#' @param email This is the email that you register in the ACLED Access portal (https://developer.acleddata.com/)
#' @param key This is the key generated by the ACLED Access portal.
#' @family API and Access
#' @examples
#' # acled_access(email = "acledexamples@gmail.com", key = "M3PWwg3DIdhHMuDiilp5") #  This is an example, you will need to input your credentials.
#' # Sys.getenv("acled_key")
#' @seealso ACLED API Access guide <https://acleddata.com/acleddatanew//wp-content/uploads/dlm_uploads/2021/11/API-User-Guide_Feb2022.pdf>
#' @export
#' @md


acled_access <- function(email,key) {

  url <- paste0("https://api.acleddata.com/check/read/?email=",email,"&","key=",key)


  response <- httr::GET(url)
  out <- httr::content(response)

  if (out$status != 200) {
    if ((out$error$message) == "Access key and email address are not authorized") {
      stop(paste0("Error: ",out$error$message, ". Error code: ", out$status,". \n"
                  ,rlang::format_error_bullets(c("Please verify your API credentials (key and email) and try again",
                                                 "If the error persists please contact us at access@acleddata.com."))))
    } else {
      stop(paste0("Error: ",out$error$message, ". Error code: ", out$status))
    }} else {

      Sys.setenv(acled_email = email)
      Sys.setenv(acled_key = key)

      return(out$messages)
    }
}
