#' @name acled_access
#' @title Store your ACLED access information into your session.
#' @description Simple function to store (through `Sys.setenv()` ) ACLED access key for the acled_api() function. If email and key is stored via acled_access, the email and key arguments for acled_api can be NULL.
#' @param email This is the email that you register in the ACLED Access portal (https://developer.acleddata.com/)
#' @param key This is the key generated by the ACLED Access portal.
#' @family API and Access
#' @examples
#' \dontrun{
#' acled_access(email = "acledexamples@gmail.com", key = "M3PWwg3DIdhHMuDiilp5")
#' Sys.getenv("acled_email")
#' Sys.getenv("acled_key")
#' }
#' @seealso ACLED API Access guide <https://acleddata.com/acleddatanew//wp-content/uploads/dlm_uploads/2021/11/API-User-Guide_Feb2022.pdf>
#' @export
#' @md


acled_access <- function(email,key) {

  url <- paste0("https://api.acleddata.com/check/read/?email=",email,"&","key=",key)


  response <- httr::GET(url)
  out <- httr::content(response)

  if (out$status != 200) {
    if ((out$error$message) == "Access key and email address are not authorized") {
      stop(paste0("Error: ",out$error$message, ". Error code: ", out$status,". \n"
                  ,rlang::format_error_bullets(c("Key and email not authorized. Please verify your API credentials (key and email) and try again",
                                                 "If the error persists please contact access@acleddata.com."))))
    } else {
      stop(paste0("Error: ",out$error$message, ". Error code: ", out$status))
    }} else {

      if(out$status == 200) {
        message("Success! Credentials authorized")
      }

      Sys.setenv(acled_email = email)
      Sys.setenv(acled_key = key)

    }

}
